name: gamified_to_do_app_bloc
description: "A gamified task management application built with Flutter and BLoC. Level up your productivity!"
publish_to: "none"
version: 0.1.0
repository: https://github.com/DrRaspec/gamified_to_do_bloc
homepage: https://github.com/DrRaspec/gamified_to_do_bloc

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # State management (BLoC)
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7

  # Dependency Injection
  get_it: ^8.0.2

  # Navigation
  go_router: ^14.6.0

  # Networking
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0

  # Storage & env
  flutter_secure_storage: ^10.0.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0

flutter:
  uses-material-design: true
  assets:
    - env/.env.dev
    - env/.env.prod
